leftnav:
- identifier: 331fbfa0-7fc8-4468-94cb-664aa1918f21
  name: Overview
  pageRef: /pages/project-instructions
  weight: 10
- identifier: 437690bf-3009-448b-80d6-f2ddbec4f06d
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: edfb01c2-8554-4414-b4fa-621df9911af3
  name: Instructions
  pageRef: /pages/project-instructions2
  weight: 30
- identifier: 1bf23223-79d3-45bb-8dc6-be3a57f03970
  name: Rubrics
  pageRef: /pages/rubrics
  weight: 40
- identifier: a159872d-3748-445c-bd63-e9638135b6d8
  name: Student Project Examples
  pageRef: /pages/student-project-examples
  weight: 50
